name: Deploy to Google Cloud Run (Fixed)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2

    - name: Set default project
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    # Backend Build and Deploy
    - name: Build Backend Image
      run: |
        docker build --no-cache --platform linux/amd64 \
          -t ${{ env.ARTIFACT_REGISTRY }}/backend:${{ github.sha }} \
          -t ${{ env.ARTIFACT_REGISTRY }}/backend:latest \
          ./backend

    - name: Push Backend Image
      run: |
        docker push ${{ env.ARTIFACT_REGISTRY }}/backend:${{ github.sha }}
        docker push ${{ env.ARTIFACT_REGISTRY }}/backend:latest

    - name: Deploy Backend to Cloud Run
      run: |
        gcloud run deploy backend \
          --image ${{ env.ARTIFACT_REGISTRY }}/backend:${{ github.sha }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --port 8000 \
          --memory 1Gi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --timeout 600 \
          --set-env-vars PORT=8000

    - name: Get Backend URL
      id: backend-url
      run: |
        # Wait a moment for service to be ready
        sleep 10
        BACKEND_URL=$(gcloud run services describe backend \
          --platform managed \
          --region ${{ env.REGION }} \
          --format 'value(status.url)')
        echo "Backend URL: $BACKEND_URL"
        echo "url=$BACKEND_URL" >> $GITHUB_OUTPUT

    # Frontend Build and Deploy
    - name: Build Frontend Image
      run: |
        docker build --platform linux/amd64 \
          --build-arg REACT_APP_API_URL=${{ steps.backend-url.outputs.url }} \
          -t ${{ env.ARTIFACT_REGISTRY }}/frontend:${{ github.sha }} \
          -t ${{ env.ARTIFACT_REGISTRY }}/frontend:latest \
          ./frontend

    - name: Push Frontend Image
      run: |
        docker push ${{ env.ARTIFACT_REGISTRY }}/frontend:${{ github.sha }}
        docker push ${{ env.ARTIFACT_REGISTRY }}/frontend:latest

    - name: Deploy Frontend to Cloud Run
      run: |
        gcloud run deploy frontend \
          --image ${{ env.ARTIFACT_REGISTRY }}/frontend:${{ github.sha }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --port 8080 \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --set-env-vars PORT=8080,REACT_APP_API_URL=${{ steps.backend-url.outputs.url }}

    - name: Show Deployment URLs
      run: |
        echo "✅ Backend URL: ${{ steps.backend-url.outputs.url }}"
        FRONTEND_URL=$(gcloud run services describe frontend \
          --platform managed \
          --region ${{ env.REGION }} \
          --format 'value(status.url)')
        echo "✅ Frontend URL: $FRONTEND_URL"
        echo ""
        echo "🚀 Deployment Complete!"